"""Candidate geometry handoff contract tests (U8).

Pins the shared seam between the Flow Path candidate detail page and the
Cycle page:

- "Send to cycle" writes the FULL merged geometry produced by the normative
  ``build_cc_geometry(sample=candidate.params)`` helper (key rename,
  r2-scaling, candidate-scaled rpm) onto the project's Compressor component
  as plain SI floats — never the bare 3 sampled params.
- The write REPLACES ``geometry_params`` wholesale (stale keys cannot
  survive), records provenance under ``geometry_source_candidate_id``,
  and saves through to the TOML store (restart survival).
- Default-on operating-point alignment sets the compressor pressure_ratio
  and the project boundary-condition mass flow to the candidate's design
  point, and rebalances the Turbine pressure_ratio through the project's
  pressure-drop chain (the capstone_c30 identity) so the next solve stays
  solvable; without alignment all three are untouched.
- Refusals: no Compressor on the canvas → synchronous 422 design-class;
  unknown candidate → 404; cross-project candidate → 404 (presents as
  not-found, mirroring the detail route guard); a failed alignment solve
  or a non-finite merged geometry → 422 with NOTHING mutated.
- "Pin as active candidate" persists ``settings.active_candidate_id`` plus
  a params snapshot to TOML (candidates are ephemeral; pins persist).
- ``GET .../manufacturability?candidate_id=`` checks the routed candidate's
  merged geometry, not the pinned/latest-VALID fallback.
- ``GET /api/jobs?project_id=`` scopes the runs list; a refused cycle run
  appears with status ``failed`` and an explore job exposes ``best_id``.

Candidates are generated by running the REAL explore endpoint at small n
(scipy Sobol', deterministic, fast) — first principles over fixtures. The
single direct ``CANDIDATE_INDEX`` seed is the non-VALID sentinel candidate,
whose generation through the API is not deterministic at small n.
"""

from __future__ import annotations

import asyncio
import dataclasses
import sys
import uuid
from pathlib import Path
from typing import Any, Dict, List

import httpx
import pytest

# Make `main` importable.
APP_DIR = Path(__file__).resolve().parent.parent
SRC_DIR = APP_DIR.parent.parent / "src"
for p in (str(APP_DIR), str(SRC_DIR)):
    if p not in sys.path:
        sys.path.insert(0, p)

from main import create_app  # noqa: E402
import jobs  # noqa: E402


MICRO = "microturbine-30kw"
AERO = "aero-demonstrator"


@pytest.fixture
def app():
    jobs.reset_for_tests()
    return create_app()


async def _wait_job(client: httpx.AsyncClient, job_id: str) -> Dict[str, Any]:
    for _ in range(400):
        r = await client.get(f"/api/jobs/{job_id}")
        if r.json()["status"] in ("done", "failed", "cancelled"):
            return r.json()
        await asyncio.sleep(0.05)
    raise AssertionError(f"job {job_id} did not finish")


async def _run_explore(
    client: httpx.AsyncClient, project_id: str, n: int = 8, seed: int = 0
) -> Dict[str, Any]:
    """Run a tiny real exploration; returns the finished job dict."""
    resp = await client.post(
        f"/api/projects/{project_id}/explore",
        json={"n_samples": n, "seed": seed},
    )
    assert resp.status_code == 200, resp.text
    job = await _wait_job(client, resp.json()["job_id"])
    assert job["status"] == "done", job
    return job


async def _get_compressor(
    client: httpx.AsyncClient, project_id: str
) -> Dict[str, Any]:
    r = await client.get(f"/api/projects/{project_id}/components")
    assert r.status_code == 200, r.text
    comp = next(
        c for c in r.json()["components"] if c["kind"] == "Compressor"
    )
    return comp


def _expected_merge(params: Dict[str, Any]):
    """Run the normative merge directly — the test's first-principles oracle."""
    from routers._meanline_geom import build_cc_geometry

    return build_cc_geometry(sample=params)


# ---------------------------------------------------------------------------
# Handoff: merged key set, plain floats, replace semantics
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_handoff_writes_full_merged_geometry_as_plain_floats(app):
    """The bag holds build_cc_geometry's output, not bare sampled params."""
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        job = await _run_explore(client, MICRO)
        best_id = job["result"]["best_id"]
        assert best_id is not None

        cand = (await client.get(f"/api/candidates/{best_id}")).json()
        # U8: the API model now exposes project_id (the in-memory dicts
        # always carried it).
        assert cand["project_id"] == MICRO

        resp = await client.post(
            f"/api/candidates/{best_id}/send-to-cycle",
            json={"project_id": MICRO},
        )
        assert resp.status_code == 200, resp.text

        comp = await _get_compressor(client, MICRO)
        gp = comp["params"]["geometry_params"]

        geom, op = _expected_merge(cand["params"])
        expected = {
            f.name: float(getattr(geom, f.name))
            for f in dataclasses.fields(geom)
            if getattr(geom, f.name) is not None
        }
        # Exact key set — the cycle builder's required fields plus the
        # explicit optionals the geometry object carries. The Sobol' key
        # name must NOT leak through (rename happened).
        assert set(gp.keys()) == set(expected.keys())
        assert "rotor_outlet_radius" not in gp
        for k, v in expected.items():
            assert isinstance(gp[k], (int, float)) and not isinstance(gp[k], bool)
            assert gp[k] == pytest.approx(v), k

        # The merged values are scaled/derived, not the raw sample: the
        # inducer dimensions must differ from the Eckardt reference (the
        # candidate r2 is far from the 0.200 m reference).
        assert gp["impeller_outlet_radius"] == pytest.approx(
            cand["params"]["rotor_outlet_radius"]
        )
        assert gp["inducer_tip_radius"] != pytest.approx(0.140)

        # RPM comes from the operating point (candidate-scaled, constant U2).
        assert comp["params"]["meanline_rpm_rpm"] == pytest.approx(op["rpm"])
        assert isinstance(comp["params"]["meanline_rpm_rpm"], float)

        # Provenance: the handoff records its source candidate as a plain
        # string — the UI chip reads exactly this key to attribute the
        # geometry.
        assert comp["params"]["geometry_source_candidate_id"] == best_id


@pytest.mark.asyncio
async def test_merged_geometry_endpoint_matches_handoff_write(app):
    """GET merged-geometry previews exactly what send-to-cycle writes."""
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        job = await _run_explore(client, MICRO)
        best_id = job["result"]["best_id"]

        mg = await client.get(
            f"/api/candidates/{best_id}/merged-geometry",
            params={"project_id": MICRO},
        )
        assert mg.status_code == 200, mg.text
        merged = mg.json()
        assert merged["sampled_keys"] == [
            "impeller_outlet_radius", "blade_count", "tip_clearance",
        ]

        sent = (
            await client.post(
                f"/api/candidates/{best_id}/send-to-cycle",
                json={"project_id": MICRO},
            )
        ).json()
        assert sent["geometry_params"] == merged["geometry_params"]
        assert sent["meanline_rpm_rpm"] == merged["meanline_rpm_rpm"]

        # Cross-project guard applies to the read endpoint too.
        r = await client.get(
            f"/api/candidates/{best_id}/merged-geometry",
            params={"project_id": AERO},
        )
        assert r.status_code == 404


@pytest.mark.asyncio
async def test_handoff_replaces_geometry_params_wholesale(app):
    """A stale extra key in the bag does not survive a re-send."""
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        job = await _run_explore(client, MICRO)
        best_id = job["result"]["best_id"]

        # Pre-seed a stale bag (component PATCH writes params top-level keys).
        comp = await _get_compressor(client, MICRO)
        r = await client.patch(
            f"/api/projects/{MICRO}/components/{comp['id']}",
            json={
                "params": {
                    "geometry_params": {
                        "impeller_outlet_radius": 0.2,
                        "stale_extra_key": 123.0,
                    }
                }
            },
        )
        assert r.status_code == 200, r.text

        resp = await client.post(
            f"/api/candidates/{best_id}/send-to-cycle",
            json={"project_id": MICRO},
        )
        assert resp.status_code == 200, resp.text

        comp = await _get_compressor(client, MICRO)
        gp = comp["params"]["geometry_params"]
        assert "stale_extra_key" not in gp
        cand = (await client.get(f"/api/candidates/{best_id}")).json()
        assert gp["impeller_outlet_radius"] == pytest.approx(
            cand["params"]["rotor_outlet_radius"]
        )


# ---------------------------------------------------------------------------
# Operating-point alignment
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_alignment_sets_pr_and_bc_mass_flow_to_design_point(app):
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        job = await _run_explore(client, MICRO)
        best_id = job["result"]["best_id"]
        cand = (await client.get(f"/api/candidates/{best_id}")).json()

        resp = await client.post(
            f"/api/candidates/{best_id}/send-to-cycle",
            json={"project_id": MICRO, "align_operating_point": True},
        )
        assert resp.status_code == 200, resp.text
        body = resp.json()
        assert body["aligned"] is True

        # First-principles oracle: solve the mean-line at the candidate's
        # design point (same solver + loss model the explore evaluator ran)
        # and require the cycle PR to be that solve's total-total PR.
        from cascade.meanline import (
            AungierCentrifugal,
            CentrifugalCompressorMeanline,
        )
        from cascade.units import Composition, Port, Q

        geom, op = _expected_merge(cand["params"])
        inlet = Port(
            pressure_total=Q(op["pressure_total_Pa"], "Pa"),
            temperature_total=Q(op["temperature_total_K"], "K"),
            mass_flow=Q(op["mass_flow_kg_per_s"], "kg/s"),
            composition=Composition.air(),
        )
        result = CentrifugalCompressorMeanline().solve(
            inlet, Q(op["rpm"], "rpm"), geom, AungierCentrifugal()
        )

        comp = await _get_compressor(client, MICRO)
        assert comp["params"]["pressure_ratio"] == pytest.approx(
            float(result.pressure_ratio_tt)
        )
        assert body["pressure_ratio"] == pytest.approx(
            float(result.pressure_ratio_tt)
        )

        proj = (await client.get(f"/api/projects/{MICRO}")).json()
        bc_mdot = proj["boundary_conditions"]["mass_flow"]
        assert bc_mdot["unit"] == "kg/s"
        assert bc_mdot["value"] == pytest.approx(op["mass_flow_kg_per_s"])

        # The Inlet component mirror stays consistent with the BC.
        r = await client.get(f"/api/projects/{MICRO}/components")
        components = r.json()["components"]
        inlet_comp = next(c for c in components if c["kind"] == "Inlet")
        assert inlet_comp["params"]["mass_flow"]["value"] == pytest.approx(
            op["mass_flow_kg_per_s"]
        )

        # The Turbine PR is rebalanced through the project's own
        # pressure-drop chain (the capstone_c30 identity: 1 atm in, 1 atm
        # out) so the aligned compressor PR cannot leave the turbine
        # over-expanding (OPEN_CYCLE_SUB_ATMOSPHERIC).
        by_kind = {c["kind"]: c.get("params", {}) for c in components}
        pr_c = float(result.pressure_ratio_tt)
        p_burner_out_atm = (
            (1.0 - by_kind["ConstantPressureLoss"]["pressure_drop_fraction"])
            * pr_c
            * (1.0 - by_kind["Recuperator"]["cold_pressure_drop_fraction"])
            * (1.0 - by_kind["Burner"]["pressure_drop_fraction"])
        )
        expected_pr_t = p_burner_out_atm * (
            1.0 - by_kind["Recuperator"]["hot_pressure_drop_fraction"]
        )
        turbine = next(c for c in components if c["kind"] == "Turbine")
        assert turbine["params"]["pressure_ratio"] == pytest.approx(
            expected_pr_t
        )
        assert body["turbine_pressure_ratio"] == pytest.approx(expected_pr_t)


@pytest.mark.asyncio
async def test_no_alignment_leaves_pr_and_bc_untouched(app):
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        comp_before = await _get_compressor(client, MICRO)
        pr_before = comp_before["params"]["pressure_ratio"]
        proj_before = (await client.get(f"/api/projects/{MICRO}")).json()
        mdot_before = proj_before["boundary_conditions"]["mass_flow"]
        r = await client.get(f"/api/projects/{MICRO}/components")
        turbine_before = next(
            c for c in r.json()["components"] if c["kind"] == "Turbine"
        )
        turbine_pr_before = turbine_before["params"]["pressure_ratio"]

        job = await _run_explore(client, MICRO)
        best_id = job["result"]["best_id"]

        resp = await client.post(
            f"/api/candidates/{best_id}/send-to-cycle",
            json={"project_id": MICRO, "align_operating_point": False},
        )
        assert resp.status_code == 200, resp.text
        body = resp.json()
        assert body["aligned"] is False
        assert body["pressure_ratio"] is None
        assert body["turbine_pressure_ratio"] is None

        comp_after = await _get_compressor(client, MICRO)
        assert comp_after["params"]["pressure_ratio"] == pr_before
        # Geometry still landed.
        assert "geometry_params" in comp_after["params"]
        proj_after = (await client.get(f"/api/projects/{MICRO}")).json()
        assert proj_after["boundary_conditions"]["mass_flow"] == mdot_before
        # The Turbine PR is untouched without alignment.
        r = await client.get(f"/api/projects/{MICRO}/components")
        turbine_after = next(
            c for c in r.json()["components"] if c["kind"] == "Turbine"
        )
        assert turbine_after["params"]["pressure_ratio"] == turbine_pr_before


# ---------------------------------------------------------------------------
# Refusals
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_handoff_without_compressor_refuses_422(app):
    """The blank aero seed can host candidates but has nothing to write to."""
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        job = await _run_explore(client, AERO)
        best_id = job["result"]["best_id"]

        resp = await client.post(
            f"/api/candidates/{best_id}/send-to-cycle",
            json={"project_id": AERO},
        )
        assert resp.status_code == 422, resp.text
        detail = resp.json()["detail"]
        assert detail["error_code"] == "NO_COMPRESSOR_COMPONENT"
        assert "Compressor" in detail["message"]


@pytest.mark.asyncio
async def test_handoff_cross_project_candidate_404(app):
    """A microturbine candidate sent to another project presents not-found."""
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        job = await _run_explore(client, MICRO)
        best_id = job["result"]["best_id"]

        resp = await client.post(
            f"/api/candidates/{best_id}/send-to-cycle",
            json={"project_id": AERO},
        )
        assert resp.status_code == 404, resp.text

        # And nothing was written anywhere: the microturbine compressor
        # bag stays clean.
        comp = await _get_compressor(client, MICRO)
        assert "geometry_params" not in comp["params"]


@pytest.mark.asyncio
async def test_handoff_unknown_candidate_404(app):
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        resp = await client.post(
            f"/api/candidates/{uuid.uuid4().hex}/send-to-cycle",
            json={"project_id": MICRO},
        )
        assert resp.status_code == 404


@pytest.mark.asyncio
async def test_handoff_non_valid_candidate_refuses_422(app):
    """A candidate whose own design point refused cannot drive the co-sim.

    Direct CANDIDATE_INDEX seed: this is the sentinel shape the explore
    evaluator emits for REGIME_OUT_OF_VALIDITY (M_rel 9.99, zeroed
    objectives) — generating one through the API is not deterministic at
    small n, so the dict mirrors the worker's construction exactly.
    """
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        cid = uuid.uuid4().hex
        jobs.CANDIDATE_INDEX[cid] = {
            "id": cid,
            "job_id": uuid.uuid4().hex,
            "project_id": MICRO,
            "index": 0,
            "params": {
                "rotor_outlet_radius": 0.03,
                "blade_count": 14,
                "tip_clearance": 2e-4,
            },
            "objectives": {
                "eta_tt": 0.0, "eta_ts": 0.0, "power": 0.0,
                "mass": 0.1, "M_rel": 9.99,
            },
            "constraints": {"M_rel_under_choke": False},
            "status": "REGIME_OUT_OF_VALIDITY",
        }
        resp = await client.post(
            f"/api/candidates/{cid}/send-to-cycle",
            json={"project_id": MICRO},
        )
        assert resp.status_code == 422, resp.text
        assert resp.json()["detail"]["error_code"] == "CANDIDATE_NOT_VALID"


@pytest.mark.asyncio
async def test_alignment_solve_failure_leaves_project_unmutated(app, monkeypatch):
    """ALIGNMENT_SOLVE_FAILED is a pure refusal: nothing sticks.

    Regression: the endpoint used to write ``geometry_params`` and
    ``meanline_rpm_rpm`` into the cached project BEFORE running the
    alignment solve, so a 422 left the rejected geometry attached in
    memory — and any later unrelated save persisted it. Validation must
    complete before the first mutation.
    """
    import copy

    import routers.candidates as candidates_mod

    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        job = await _run_explore(client, MICRO)
        best_id = job["result"]["best_id"]

        comp_before = copy.deepcopy(await _get_compressor(client, MICRO))
        proj_before = copy.deepcopy(
            (await client.get(f"/api/projects/{MICRO}")).json()
        )

        def _boom(geom, op):  # noqa: ANN001
            raise RuntimeError("forced alignment-solve failure")

        monkeypatch.setattr(candidates_mod, "_design_point_solve", _boom)

        resp = await client.post(
            f"/api/candidates/{best_id}/send-to-cycle",
            json={"project_id": MICRO, "align_operating_point": True},
        )
        assert resp.status_code == 422, resp.text
        detail = resp.json()["detail"]
        assert detail["error_code"] == "ALIGNMENT_SOLVE_FAILED"

        # The Compressor bag is byte-identical to before the call — the
        # rejected geometry never touched the cached project.
        comp_after = await _get_compressor(client, MICRO)
        assert comp_after == comp_before
        assert "geometry_params" not in comp_after["params"]
        assert "geometry_source_candidate_id" not in comp_after["params"]
        # ...and the whole project dict (BC mass flow, turbine PR, all
        # components) is untouched too.
        proj_after = (await client.get(f"/api/projects/{MICRO}")).json()
        assert proj_after == proj_before


@pytest.mark.asyncio
async def test_handoff_nonfinite_merged_geometry_refuses_422(app, monkeypatch):
    """A NaN from a degenerate merge refuses — never written to the bag.

    The serialization loop in ``_merged_cc_geometry`` guards every field
    with ``math.isfinite``; the 422 names the offending field so the user
    can see which dimension degenerated.
    """
    import dataclasses as dc

    import routers._meanline_geom as mg

    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        job = await _run_explore(client, MICRO)
        best_id = job["result"]["best_id"]

        real_build = mg.build_cc_geometry

        def _nan_build(sample=None, project_params=None):  # noqa: ANN001
            geom, op = real_build(sample=sample, project_params=project_params)
            # NaN survives the dataclass's own range checks (NaN < 0 is
            # False) — exactly the silent-poison path the guard closes.
            return dc.replace(geom, tip_clearance=float("nan")), op

        monkeypatch.setattr(mg, "build_cc_geometry", _nan_build)

        resp = await client.post(
            f"/api/candidates/{best_id}/send-to-cycle",
            json={"project_id": MICRO},
        )
        assert resp.status_code == 422, resp.text
        detail = resp.json()["detail"]
        assert detail["error_code"] == "CANDIDATE_GEOMETRY_INVALID"
        assert "tip_clearance" in detail["message"]

        # Nothing landed in the bag.
        comp = await _get_compressor(client, MICRO)
        assert "geometry_params" not in comp["params"]


# ---------------------------------------------------------------------------
# Persistence: pins persist; the handoff survives a restart
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_pin_survives_projects_reload(app):
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        job = await _run_explore(client, MICRO)
        best_id = job["result"]["best_id"]
        cand = (await client.get(f"/api/candidates/{best_id}")).json()

        resp = await client.post(
            f"/api/candidates/{best_id}/pin", json={"project_id": MICRO}
        )
        assert resp.status_code == 200, resp.text
        assert resp.json()["active_candidate_id"] == best_id

        # Simulate a server restart: drop the cache, re-read from disk.
        jobs.PROJECTS.reload()

        proj = (await client.get(f"/api/projects/{MICRO}")).json()
        settings = proj["settings"]
        assert settings["active_candidate_id"] == best_id
        snapshot = settings["pinned_candidates"][best_id]
        assert snapshot["params"]["rotor_outlet_radius"] == pytest.approx(
            cand["params"]["rotor_outlet_radius"]
        )
        assert snapshot["objectives"]["eta_tt"] == pytest.approx(
            cand["objectives"]["eta_tt"]
        )
        assert snapshot["status"] == "VALID"


@pytest.mark.asyncio
async def test_handoff_survives_projects_reload(app):
    """Pins the save-through requirement: an unsaved handoff dies on restart."""
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        job = await _run_explore(client, MICRO)
        best_id = job["result"]["best_id"]

        sent = (
            await client.post(
                f"/api/candidates/{best_id}/send-to-cycle",
                json={"project_id": MICRO},
            )
        ).json()

        jobs.PROJECTS.reload()

        comp = await _get_compressor(client, MICRO)
        gp = comp["params"]["geometry_params"]
        for k, v in sent["geometry_params"].items():
            assert gp[k] == pytest.approx(v), k
        assert comp["params"]["meanline_rpm_rpm"] == pytest.approx(
            sent["meanline_rpm_rpm"]
        )
        assert comp["params"]["pressure_ratio"] == pytest.approx(
            sent["pressure_ratio"]
        )
        # Provenance survives the round-trip as a plain string.
        assert comp["params"]["geometry_source_candidate_id"] == best_id


@pytest.mark.asyncio
async def test_detach_geometry_removes_bag_and_survives_reload(app):
    """DELETE .../components/{cid}/geometry strips the handoff cleanly."""
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        job = await _run_explore(client, MICRO)
        best_id = job["result"]["best_id"]
        await client.post(
            f"/api/candidates/{best_id}/send-to-cycle",
            json={"project_id": MICRO},
        )
        comp = await _get_compressor(client, MICRO)
        assert "geometry_params" in comp["params"]

        r = await client.delete(
            f"/api/projects/{MICRO}/components/{comp['id']}/geometry"
        )
        assert r.status_code == 204, r.text

        jobs.PROJECTS.reload()

        comp = await _get_compressor(client, MICRO)
        assert "geometry_params" not in comp["params"]
        assert "meanline_rpm_rpm" not in comp["params"]
        # Detach removes only the geometry bag — the aligned operating
        # point (an explicit user-confirmed write) stays.
        assert "pressure_ratio" in comp["params"]

        # Unknown component → 404.
        r = await client.delete(
            f"/api/projects/{MICRO}/components/nope/geometry"
        )
        assert r.status_code == 404


# ---------------------------------------------------------------------------
# Manufacturability candidate routing
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_manufacturability_candidate_id_overrides_fallback(app):
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        await _run_explore(client, MICRO)
        cands: List[Dict[str, Any]] = (
            await client.get("/api/candidates")
        ).json()
        valid = [c for c in cands if c["status"] == "VALID"]
        assert len(valid) >= 2
        # Two candidates with distinct outlet radii.
        a, b = valid[0], valid[1]
        assert (
            a["params"]["rotor_outlet_radius"]
            != b["params"]["rotor_outlet_radius"]
        )

        # Pin A so the fallback heuristic resolves to A...
        r = await client.post(
            f"/api/candidates/{a['id']}/pin", json={"project_id": MICRO}
        )
        assert r.status_code == 200

        # ...then explicitly route B: the verdict must be B's geometry.
        resp = await client.get(
            f"/api/projects/{MICRO}/manufacturability",
            params={"candidate_id": b["id"]},
        )
        assert resp.status_code == 200, resp.text
        report = resp.json()
        assert report["candidate_id"] == b["id"]
        assert report["geometry"]["impeller_outlet_radius_m"] == pytest.approx(
            b["params"]["rotor_outlet_radius"]
        )

        # The un-routed call falls back to the pinned candidate A.
        fallback = (
            await client.get(f"/api/projects/{MICRO}/manufacturability")
        ).json()
        assert fallback["candidate_id"] == a["id"]


@pytest.mark.asyncio
async def test_manufacturability_unknown_candidate_404(app):
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        resp = await client.get(
            f"/api/projects/{MICRO}/manufacturability",
            params={"candidate_id": uuid.uuid4().hex},
        )
        assert resp.status_code == 404


@pytest.mark.asyncio
async def test_put_manufacturability_overrides_returns_report(app):
    """PUT /overrides persists the map and re-runs the check — 200, never 404.

    Regression: the PUT handler used to delegate to the GET *endpoint*
    function, whose ``Query(None)`` default object leaked into the
    candidate lookup (``CANDIDATE_INDEX.get(<Query>)``) and 404'd every
    call. The override path must resolve with candidate_id=None semantics.
    """
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        resp = await client.put(
            f"/api/projects/{MICRO}/manufacturability/overrides",
            json={"overrides": {"le_thickness_min": 0.05e-3}},
        )
        assert resp.status_code == 200, resp.text
        report = resp.json()
        # The override is echoed as applied to the rule set.
        assert report["overrides_used"]["le_thickness_min"] == pytest.approx(
            0.05e-3
        )
        # No candidates exist on the fresh seed → defaults fallback.
        assert report["candidate_id"] is None

        # The map persisted: a plain GET re-applies it.
        again = await client.get(f"/api/projects/{MICRO}/manufacturability")
        assert again.status_code == 200, again.text
        assert again.json()["overrides_used"][
            "le_thickness_min"
        ] == pytest.approx(0.05e-3)


# ---------------------------------------------------------------------------
# Jobs list (runs page wiring)
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_jobs_list_scopes_by_project_and_shows_refusal_failed(app):
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://t") as client:
        # A refused cycle run on the blank aero seed (U1 refusal contract).
        r = await client.post(f"/api/projects/{AERO}/cycle/solve")
        assert r.status_code == 200, r.text
        refused = await _wait_job(client, r.json()["job_id"])
        assert refused["status"] == "failed"

        # A real explore on the microturbine.
        explore_job = await _run_explore(client, MICRO)

        aero_jobs = (
            await client.get("/api/jobs", params={"project_id": AERO})
        ).json()
        assert [j["kind"] for j in aero_jobs] == ["cycle"]
        assert aero_jobs[0]["status"] == "failed"
        # Refusal signature: error is None + structured failure envelope.
        assert aero_jobs[0]["error"] is None
        assert aero_jobs[0]["result"]["failure"]["kind"] == "design"

        micro_jobs = (
            await client.get("/api/jobs", params={"project_id": MICRO})
        ).json()
        assert [j["kind"] for j in micro_jobs] == ["explore"]
        # The explore job exposes best_id for the candidate detail link.
        assert (
            micro_jobs[0]["result"]["best_id"]
            == explore_job["result"]["best_id"]
        )

        # Unscoped list still returns everything (legacy behaviour),
        # newest first — the runs page reads top-down. The explore job was
        # created after the refused cycle run, so it must lead.
        all_jobs = (await client.get("/api/jobs")).json()
        assert len(all_jobs) == 2
        assert [j["id"] for j in all_jobs] == [
            micro_jobs[0]["id"],
            aero_jobs[0]["id"],
        ]
        created = [j["created_at"] for j in all_jobs]
        assert created == sorted(created, reverse=True)
