"""Deterministic TOML serializer for `.cascade` v1.

The whole point of this module: editing one field in a Pydantic ``Project``
and dumping must produce a one-line diff in the resulting TOML. So we:

* Emit sections in a fixed order (``meta``, ``boundary_conditions``,
  ``settings``, ``components``, ``edges``). This is the order a human reads.
* Inside every dict whose order isn't semantically meaningful, sort keys.
* Lists of components / edges are emitted as **arrays of tables** (the TOML
  ``[[components]]`` syntax) — those split onto multiple lines and diff well.
* Datetimes are written as RFC-3339 strings (with `Z` suffix for UTC),
  not raw ``datetime`` objects, so the format is stable across Pythons.
* Line endings normalised to ``\n`` and the file always ends with a newline.

We use stdlib ``tomllib`` on Python 3.11+ and the ``tomli`` shim on 3.9/3.10.
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from typing import Any, Dict, List

import tomli_w

if sys.version_info >= (3, 11):
    import tomllib  # type: ignore[import-not-found]
else:
    import tomli as tomllib  # type: ignore[no-redef]

from .schema import (
    CASCADE_VERSION,
    SCHEMA_VERSION,
    ComponentRecord,
    EdgeRecord,
    Project,
    ProjectMeta,
)

# The order sections are emitted in. Top-level scalar keys (``id``) come first.
_SECTION_ORDER = ("meta", "boundary_conditions", "settings", "components", "edges")

# Keys whose order is semantically meaningful and must NOT be alpha-sorted.
# (Right now: nothing — every dict we serialize is alpha-sortable. We keep
# this hook for future schema additions like ordered cycle stages.)
_PRESERVE_ORDER_KEYS: frozenset = frozenset()

_FILE_HEADER = (
    "# .cascade project file v1\n"
    "# Generated by Cascade {version}. Edit by hand or via the UI — both work.\n"
    "# Stable, sorted keys: a single-field edit produces a single-line diff.\n"
    "\n"
)


def _iso_z(dt: datetime) -> str:
    """Render a datetime as RFC-3339 with a `Z` UTC suffix.

    TOML allows native ``datetime`` literals but ``tomli_w`` renders them as
    ``YYYY-MM-DDTHH:MM:SS+00:00``. We prefer the trailing-``Z`` form because
    it's what the rest of the API uses (matches JS ``Date.toISOString``).
    """

    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    else:
        dt = dt.astimezone(timezone.utc)
    s = dt.isoformat()
    if s.endswith("+00:00"):
        s = s[: -len("+00:00")] + "Z"
    return s


def _sort_recursive(value: Any) -> Any:
    """Return ``value`` with every dict's keys alpha-sorted, recursively.

    Lists are mapped element-wise (each element may be a dict). Scalars pass
    through. Datetimes are converted to RFC-3339 ``Z`` strings so we don't
    have to round-trip through tomli_w's datetime serializer.
    """

    if isinstance(value, dict):
        out: Dict[str, Any] = {}
        for k in sorted(value.keys()):
            v = value[k]
            out[k] = _sort_recursive(v)
        return out
    if isinstance(value, list):
        return [_sort_recursive(v) for v in value]
    if isinstance(value, datetime):
        return _iso_z(value)
    return value


def _meta_to_toml_dict(m: ProjectMeta) -> Dict[str, Any]:
    """Render ``ProjectMeta`` into a stable dict ready for tomli_w.

    We explicitly enumerate fields rather than using ``model_dump()`` so that
    new schema fields don't silently leak into existing files and break the
    byte-for-byte round-trip.
    """

    d: Dict[str, Any] = {
        "created_at": _iso_z(m.created_at),
        "description": m.description,
        "kind": m.kind,
        "name": m.name,
        "cascade_version": m.cascade_version,
        "schema_version": m.schema_version,
        "updated_at": _iso_z(m.updated_at),
        "working_fluid": m.working_fluid,
    }
    if m.last_run_status is not None:
        d["last_run_status"] = m.last_run_status
    # Forward any extra fields (``ConfigDict(extra='allow')``) — sorted.
    extras = m.model_extra or {}
    for k in sorted(extras.keys()):
        if k not in d:
            d[k] = _sort_recursive(extras[k])
    return d


def _component_to_toml_dict(c: ComponentRecord) -> Dict[str, Any]:
    d: Dict[str, Any] = {
        "id": c.id,
        "kind": c.kind,
        "name": c.name,
        "params": _sort_recursive(c.params),
        "position": _sort_recursive(c.position),
    }
    extras = c.model_extra or {}
    for k in sorted(extras.keys()):
        if k not in d:
            d[k] = _sort_recursive(extras[k])
    return d


def _edge_to_toml_dict(e: EdgeRecord) -> Dict[str, Any]:
    d: Dict[str, Any] = {
        "id": e.id,
        "source": e.source,
        "source_port": e.source_port,
        "target": e.target,
        "target_port": e.target_port,
    }
    extras = e.model_extra or {}
    for k in sorted(extras.keys()):
        if k not in d:
            d[k] = _sort_recursive(extras[k])
    return d


def _build_toml_dict(p: Project) -> Dict[str, Any]:
    """Build the canonical dict shape that ``tomli_w`` will dump.

    Key order *here* directly drives section order in the TOML file. Within
    each section, we let ``_sort_recursive`` sort the keys.
    """

    toml_dict: Dict[str, Any] = {
        # Top-level scalars first so they appear above the [meta] header.
        "id": p.id,
        # Then sections in the fixed order.
        "meta": _meta_to_toml_dict(p.meta),
        "boundary_conditions": _sort_recursive(p.boundary_conditions),
        "settings": _sort_recursive(p.settings),
        # Components / edges as arrays-of-tables (``[[components]]``).
        "components": [_component_to_toml_dict(c) for c in p.components],
        "edges": [_edge_to_toml_dict(e) for e in p.edges],
    }
    return toml_dict


def project_to_toml(project: Project) -> str:
    """Serialize a Project to a deterministic, sorted, LF-terminated TOML string.

    Round-trip stability is asserted in ``tests/project/test_toml_roundtrip.py``:
    ``project_to_toml(project_from_toml(s)) == s`` for every demo project.
    """

    toml_dict = _build_toml_dict(project)
    body = tomli_w.dumps(toml_dict)
    text = _FILE_HEADER.format(version=CASCADE_VERSION) + body
    # tomli_w already uses LF; just be defensive against Windows.
    text = text.replace("\r\n", "\n")
    if not text.endswith("\n"):
        text += "\n"
    return text


def project_from_toml(text: str) -> Project:
    """Parse a `.cascade.toml` string into a validated Project.

    Tolerates legacy files written before ``[meta]`` was a section by
    pulling top-level scalars (``name``, ``kind``, …) into ``meta`` for
    backwards compatibility. Schema-version 1 files do not need this path.
    """

    data = tomllib.loads(text)
    if "id" not in data:
        raise ValueError("`.cascade.toml` is missing the top-level `id` field.")

    meta_dict: Dict[str, Any] = dict(data.get("meta", {}))

    # Back-compat: hoist any top-level meta-ish keys into [meta] if a file
    # predates this schema (e.g. user hand-wrote without [meta]).
    for legacy_key in (
        "name",
        "description",
        "kind",
        "working_fluid",
        "created_at",
        "updated_at",
        "last_run_status",
    ):
        if legacy_key in data and legacy_key not in meta_dict:
            meta_dict[legacy_key] = data[legacy_key]

    # Datetimes can arrive as tomllib's datetime or as strings — Pydantic
    # accepts both via the standard datetime validator.
    legacy = {
        "id": data["id"],
        "name": meta_dict.get("name", data["id"]),
        "description": meta_dict.get("description", ""),
        "kind": meta_dict.get("kind", "blank"),
        "working_fluid": meta_dict.get("working_fluid", "air"),
        "created_at": meta_dict.get("created_at"),
        "updated_at": meta_dict.get("updated_at"),
        "last_run_status": meta_dict.get("last_run_status"),
        "components": data.get("components", []),
        "edges": data.get("edges", []),
        "boundary_conditions": data.get("boundary_conditions", {}),
        "settings": data.get("settings", {}),
    }
    return Project.from_legacy_dict(legacy)
