import type { Metadata } from "next";
import Link from "next/link";
import { CodeBlock, CodeTabs, DocPage, ParamRow, ParamTable } from "@/components/docs";
import { Callout, Section } from "@/components/learn/content";

export const metadata: Metadata = { title: "Projects & the .cascade format" };

const EXAMPLE_TOML = `# .cascade project file v1
# Generated by Cascade 0.1.0. Edit by hand or via the UI — both work.

id = "microturbine-30kw"

[meta]
name = "Microturbine 30 kW"
description = "Recuperated Brayton matched to the Capstone C30 spec."
kind = "microturbine"
working_fluid = "air"
created_at = "2026-05-12T09:30:00Z"
updated_at = "2026-06-02T14:11:08Z"
cascade_version = "0.1.0"
schema_version = 1

[boundary_conditions]
composition = "air"
mass_flow = { value = 0.31, unit = "kg/s" }
pressure_total = { value = 101.325, unit = "kPa" }
temperature_total = { value = 288.15, unit = "K" }

[settings]
generator_efficiency = 0.97
mechanical_efficiency = 0.98

[[components]]
id = "inlet"
kind = "Inlet"
name = "Inlet"
position = { x = 40.0, y = 240.0 }

[components.params]
composition = "air"
mass_flow = { value = 0.31, unit = "kg/s" }
pressure_total = { value = 101.325, unit = "kPa" }
temperature_total = { value = 288.15, unit = "K" }

[[components]]
id = "compressor"
kind = "Compressor"
name = "C1"
position = { x = 360.0, y = 240.0 }

[components.params]
efficiency_isentropic = 0.79
pressure_ratio = 4.0

[[edges]]
id = "e1"
source = "inlet"
source_port = "out"
target = "compressor"
target_port = "in"`;

export default function ProjectsPage() {
  return (
    <DocPage slug="projects">
      <Section id="philosophy" title="Files, not a database">
        <p>
          A Cascade project is a TOML file on disk. Not an export of a
          database, not a binary blob with a proprietary reader — the file{" "}
          <em>is</em> the project. Edit it by hand or through the UI; both
          paths write the same bytes.
        </p>
        <p>This buys you three things that proprietary suites can&apos;t offer:</p>
        <ul className="ml-5 list-disc space-y-2">
          <li>
            <strong>Diffable.</strong> Keys are sorted and serialization is
            deterministic, so a single-field edit produces a single-line diff.
            Changing a pressure ratio looks like changing a pressure ratio.
          </li>
          <li>
            <strong>Reviewable.</strong> Design changes go through pull
            requests like code. Your colleague reviews{" "}
            <code className="font-mono text-[13px]">pressure_ratio = 4.0 → 4.5</code>,
            with the units right there in the file.
          </li>
          <li>
            <strong>Durable.</strong> TOML will be readable in thirty years.
            Your designs outlive any vendor.
          </li>
        </ul>
        <Callout kind="note" title="Collaboration in v0.1 is asynchronous">
          Branch, diff, and PR — git is the collaboration layer today.
          Real-time multi-user co-editing is a tracked gap (
          <code className="font-mono text-[13px]">KG-PLAT-01</code>), planned,
          not shipped.
        </Callout>
      </Section>

      <Section id="location" title="Where projects live">
        <CodeBlock
          lang="bash"
          bare
          code={`~/.cascade/projects/
├── microturbine-30kw.cascade.toml
├── sco2-test-loop.cascade.toml
└── at-100kw-prototype.cascade.toml`}
        />
        <p>
          The directory is configurable with{" "}
          <code className="font-mono text-[13px]">CASCADE_PROJECTS_DIR</code>.
          Pointing it at a git repository is the intended workflow:
        </p>
        <CodeBlock
          lang="bash"
          title="terminal"
          code={`export CASCADE_PROJECTS_DIR=~/work/turbine-designs
cd ~/work/turbine-designs && git init
# ... design in Cascade, then:
git add projects/ && git commit -m "Raise PR to 4.5 on the 30 kW unit"`}
        />
      </Section>

      <Section id="anatomy" title="Anatomy of a project file">
        <p>
          Here is a trimmed version of the seeded microturbine project —
          the real file has more components (recuperator, burner, turbine,
          exhaust), but every structural element appears below:
        </p>
        <CodeBlock
          lang="toml"
          title="microturbine-30kw.cascade.toml"
          code={EXAMPLE_TOML}
        />
        <ParamTable title="Top-level tables">
          <ParamRow name="id" type="string" required>
            The project slug — also the filename and the URL segment in the
            web app.
          </ParamRow>
          <ParamRow name="[meta]" type="table">
            Name, description, timestamps (RFC 3339, always UTC{" "}
            <code className="font-mono text-[13px]">Z</code>), the project{" "}
            <code className="font-mono text-[13px]">kind</code>{" "}
            (microturbine | sco2 | aero | blank), the working fluid, and a{" "}
            <code className="font-mono text-[13px]">schema_version</code> so
            future Cascade versions can migrate old files explicitly.
          </ParamRow>
          <ParamRow name="[boundary_conditions]" type="table">
            Inlet total pressure, total temperature, mass flow, and gas
            composition. Editing the Inlet component in the UI mirrors onto
            this table automatically.
          </ParamRow>
          <ParamRow name="[settings]" type="table">
            Project-wide knobs: mechanical and generator efficiency,
            per-project manufacturability rule overrides, pinned candidates.
          </ParamRow>
          <ParamRow name="[[components]]" type="array of tables">
            One entry per component on the cycle canvas. Each has a stable{" "}
            <code className="font-mono text-[13px]">id</code>, a{" "}
            <code className="font-mono text-[13px]">kind</code> (Inlet,
            Outlet, Compressor, Turbine, Burner, Recuperator, Intercooler,
            Mixer, Splitter, ConstantPressureLoss, Shaft), a display name, a
            canvas position, and its physics parameters under{" "}
            <code className="font-mono text-[13px]">[components.params]</code>.
          </ParamRow>
          <ParamRow name="[[edges]]" type="array of tables">
            The connections between components — which outlet feeds which
            inlet. Together with components, this is the whole cycle topology.
          </ParamRow>
        </ParamTable>
      </Section>

      <Section id="units" title="How units are written">
        <p>
          Every physical quantity in the file is a two-field inline table —
          value plus unit — so the file is unambiguous without a manual:
        </p>
        <CodeBlock
          lang="toml"
          bare
          code={`pressure_total = { value = 101.325, unit = "kPa" }   # a physical quantity
pressure_ratio = 4.0                                  # a dimensionless ratio`}
        />
        <p>
          Dimensionless numbers (ratios, efficiencies, counts) are plain
          floats. The serializer round-trips exactly:{" "}
          <code className="font-mono text-[13px]">
            project_to_toml(project_from_toml(s)) == s
          </code>
          . See{" "}
          <Link href="/docs/units" className="font-medium text-brand-text hover:underline">
            Units &amp; quantities
          </Link>{" "}
          for what happens when units disagree (short version: Cascade
          refuses).
        </p>
      </Section>

      <Section id="scripting" title="Reading and writing projects from code">
        <CodeTabs
          tabs={[
            {
              label: "Python",
              lang: "python",
              code: `from cascade.project import load_project, save_project, list_projects

# Load by slug from CASCADE_PROJECTS_DIR (default ~/.cascade)
proj = load_project("microturbine-30kw")
print(proj.meta.name)        # "Microturbine 30 kW"

# Or work with raw TOML strings
from cascade.project import project_from_toml, project_to_toml
toml_str = project_to_toml(proj)
roundtrip = project_from_toml(toml_str)

save_project(proj)
print([p.id for p in list_projects()])`,
            },
            {
              label: "HTTP",
              lang: "http",
              code: `GET    /api/projects                 # list all projects
GET    /api/projects/{project_id}    # full detail: components, edges, BCs
POST   /api/projects                 # create from a template
PATCH  /api/projects/{project_id}    # rename, edit settings or BCs
DELETE /api/projects/{project_id}`,
            },
          ]}
        />
        <Callout kind="warning" title="Writes are immediate">
          Component edits made through the API persist to the TOML file right
          away — there is no separate “save” step to forget. If the projects
          directory is a git repo, <code className="font-mono text-[13px]">git diff</code>{" "}
          always shows the live state.
        </Callout>
      </Section>

      <Section id="seeded" title="The three seeded projects">
        <ul className="ml-5 list-disc space-y-2">
          <li>
            <strong>Microturbine 30 kW</strong> — recuperated Brayton matched
            to the published Capstone C30 spec (PR 4.0, TIT ≈ 811 K,
            recuperator ε 0.86). This is also validation case CYC-3.
          </li>
          <li>
            <strong>sCO₂ Test Loop</strong> — a simple supercritical-CO₂
            Brayton (7.4 MPa / 305 K inlet, PR 3.0, heater to 873 K) for
            high-pressure prototype work.
          </li>
          <li>
            <strong>AT-100 kW Prototype</strong> — a natural-gas 100 kW
            machine (PR 5.0, TIT 1255 K, recuperator ε 0.87) with its cycle
            parameters left tunable on purpose.
          </li>
        </ul>
        <p>
          Seeding is idempotent: deleting a seeded project keeps it deleted
          until you wipe the projects directory.
        </p>
      </Section>
    </DocPage>
  );
}
