"""Volute (scroll / casing) mesh generator.

For a centrifugal compressor or radial turbine the volute is the
collecting / distributing scroll. Three classic forms exist:

1. Log-spiral with circular cross-section (the default in this module).
2. Constant-section.
3. Custom spline.

This module ships the log-spiral default; the cross-section is circular
with radius proportional to ``sqrt((θ_360 - θ) / θ_360)`` so the area
ratio tapers linearly to the tongue. The mesh is generated by sweeping a
circular cross-section along the spiral path.

A small "tongue" (cut-water) is added at θ=0 to give the volute a
recognizable silhouette.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import List, Tuple

import numpy as np
import trimesh

from cascade.geometry.export import apply_casing_material
from cascade.geometry.impeller import LOD_RESOLUTION
from cascade.units import Quantity


@dataclass(frozen=True)
class VoluteGeometry:
    """Geometric description of a log-spiral volute.

    Attributes:
        r_base: base radius where the volute starts (at θ=0, just outside
            the diffuser exit) [m].
        alpha_volute_rad: log-spiral angle (a.k.a. swirl angle) [rad].
            Typical value: ``π/8`` (≈ 22.5°). Larger → more aggressive
            spiral; smaller → tighter wrap.
        cross_section_max_radius: maximum cross-section radius at the
            "design" θ (typically θ = π / 2) [m]. The cross-section
            scales with the area distribution.
        outlet_axial_extent: how far the discharge cone sticks out in the
            axial / tangential direction [m]. Cosmetic; not load-bearing
            in the mesh.
    """

    r_base: float
    alpha_volute_rad: float
    cross_section_max_radius: float
    outlet_axial_extent: float = 0.0


def _spiral_centerline(
    geometry: VoluteGeometry,
    n_theta: int,
) -> np.ndarray:
    """Sample the volute spiral centerline.

    Returns ``(n_theta, 3)`` array of (x, y, z) points. The spiral
    sweeps from θ=0 to θ=2π in the z=0 plane:
        R(θ) = R_0 · exp(θ · tan(α))
    """
    theta = np.linspace(0.0, 2.0 * math.pi, n_theta, endpoint=True)
    R = geometry.r_base * np.exp(theta * math.tan(geometry.alpha_volute_rad))
    pts = np.stack([R * np.cos(theta), R * np.sin(theta), np.zeros_like(theta)], axis=1)
    return pts, theta


def _cross_section_radius(theta: np.ndarray, R_max: float) -> np.ndarray:
    """Cross-section radius along the volute.

    The area A(θ) is linear in θ from 0 at the tongue (θ=0) to maximum at
    θ=2π. For a circular cross-section the radius scales as sqrt(θ/2π).
    To avoid a zero-radius singularity at the tongue we floor the
    distribution at 10% of R_max.
    """
    frac = np.clip(theta / (2.0 * math.pi), 0.0, 1.0)
    r_cs = R_max * np.sqrt(np.maximum(frac, 0.0))
    r_cs = np.maximum(r_cs, 0.10 * R_max)
    return r_cs


def _sweep_circular_cross_section(
    centerline: np.ndarray,
    theta_centerline: np.ndarray,
    cross_radii: np.ndarray,
    n_section: int,
) -> np.ndarray:
    """Sweep a circular cross-section along the centerline.

    At each centerline point we place a circle in the plane perpendicular
    to the centerline tangent. The orientation is determined so the
    "outward normal" of the circle points radially outward from the
    machine centerline (i.e. away from r=0 in the world frame).

    Returns ``(n_centerline, n_section, 3)`` array.
    """
    n_c = len(centerline)
    # Tangent direction along the centerline (use central differences with
    # forward/backward at the endpoints).
    tangent = np.zeros_like(centerline)
    tangent[1:-1] = centerline[2:] - centerline[:-2]
    tangent[0] = centerline[1] - centerline[0]
    tangent[-1] = centerline[-1] - centerline[-2]
    tangent_norm = np.linalg.norm(tangent, axis=1, keepdims=True)
    tangent = tangent / np.maximum(tangent_norm, 1e-9)

    # For a planar spiral in the z=0 plane the binormal is +z and the
    # principal normal lies in the z=0 plane perpendicular to tangent.
    binormal = np.tile(np.array([0.0, 0.0, 1.0]), (n_c, 1))
    normal = np.cross(binormal, tangent)
    normal_norm = np.linalg.norm(normal, axis=1, keepdims=True)
    normal = normal / np.maximum(normal_norm, 1e-9)

    phi = np.linspace(0.0, 2.0 * math.pi, n_section, endpoint=True)
    cos_p = np.cos(phi)
    sin_p = np.sin(phi)

    pts = np.empty((n_c, n_section, 3), dtype=float)
    for i in range(n_c):
        r = cross_radii[i]
        # The cross-section is a circle: center + r*(cos·normal + sin·binormal)
        pts[i] = centerline[i] + r * (
            cos_p[:, None] * normal[i] + sin_p[:, None] * binormal[i]
        )
    return pts


def _triangulate_tube(pts: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """Triangulate a structured (n_along, n_around, 3) tube grid."""
    rows, cols, _ = pts.shape
    vertices = pts.reshape(-1, 3)
    faces: List[Tuple[int, int, int]] = []
    for i in range(rows - 1):
        for j in range(cols - 1):
            a = i * cols + j
            b = (i + 1) * cols + j
            c = (i + 1) * cols + (j + 1)
            d = i * cols + (j + 1)
            faces.append((a, b, c))
            faces.append((a, c, d))
    return vertices, np.asarray(faces, dtype=np.int64)


def _cap_circle(
    center: np.ndarray,
    radius_cap: float,
    normal: np.ndarray,
    binormal: np.ndarray,
    n_section: int,
) -> Tuple[np.ndarray, np.ndarray]:
    """Triangle-fan disc that caps an end of the tube."""
    phi = np.linspace(0.0, 2.0 * math.pi, n_section, endpoint=True)
    cos_p = np.cos(phi)
    sin_p = np.sin(phi)
    rim = center + radius_cap * (
        cos_p[:, None] * normal + sin_p[:, None] * binormal
    )
    vertices = np.concatenate([center[None, :], rim], axis=0)
    faces = []
    for j in range(n_section - 1):
        # Triangle fan from center (vertex 0) to consecutive rim points.
        faces.append((0, 1 + j, 1 + j + 1))
    return vertices, np.asarray(faces, dtype=np.int64)


def volute_mesh_impl(
    geometry: VoluteGeometry,
    lod_key: str,
) -> trimesh.Trimesh:
    """Build the canonical volute mesh.

    The result is a closed-ish surface — the inlet and outlet ends of the
    spiral tube are capped with triangle fans so the mesh is watertight
    enough to be a useful glb.
    """
    if lod_key not in LOD_RESOLUTION:
        raise ValueError(f"unknown LOD {lod_key!r}")
    n_along, n_section = LOD_RESOLUTION[lod_key]
    # Volute tube needs sensible minimums.
    n_along = max(n_along, 24)
    n_section = max(n_section, 16)

    centerline, theta = _spiral_centerline(geometry, n_along)
    cross_radii = _cross_section_radius(theta, geometry.cross_section_max_radius)

    pts = _sweep_circular_cross_section(centerline, theta, cross_radii, n_section)
    vertices, faces = _triangulate_tube(pts)

    # Compute caps at both ends (the tongue end and the discharge end).
    # Tangent / normal / binormal at the endpoints — recompute locally so
    # cap vertices align with the rim verts.
    def cap_frame(idx: int):
        if idx == 0:
            tang = centerline[1] - centerline[0]
        else:
            tang = centerline[idx] - centerline[idx - 1]
        tang = tang / max(np.linalg.norm(tang), 1e-9)
        binorm = np.array([0.0, 0.0, 1.0])
        norm = np.cross(binorm, tang)
        norm = norm / max(np.linalg.norm(norm), 1e-9)
        return centerline[idx], norm, binorm

    # Cap at idx 0 (the tongue):
    c0, n0, b0 = cap_frame(0)
    cap0_v, cap0_f = _cap_circle(
        c0, cross_radii[0], n0, b0, n_section,
    )

    # Cap at idx -1 (the outlet):
    c1, n1, b1 = cap_frame(len(centerline) - 1)
    cap1_v, cap1_f = _cap_circle(
        c1, cross_radii[-1], n1, b1, n_section,
    )

    v_list = [vertices, cap0_v, cap1_v]
    f_list = [faces, cap0_f, cap1_f]
    offsets = np.cumsum([0] + [len(v) for v in v_list[:-1]])
    all_v = np.concatenate(v_list, axis=0)
    all_f = np.concatenate(
        [f + o for f, o in zip(f_list, offsets)], axis=0
    )

    mesh = trimesh.Trimesh(vertices=all_v, faces=all_f, process=False)
    mesh.merge_vertices(merge_norm=True)
    mesh.fix_normals()
    _ = mesh.vertex_normals

    apply_casing_material(mesh)
    return mesh
