"""API 684 rotor-dynamics PDF report generator (W-16).

Produces a one-page US-Letter PDF from rotor solver results.  Uses only
``reportlab`` (pure-Python, no system deps beyond the venv install).

Acceptance criteria addressed here:
- AC1: the function returns a valid PDF binary (Content-Type set by the caller).
- AC2: "PRELIMINARY — NOT FOR CERTIFICATION" watermark, diagonal, semi-transparent.
- AC3: critical-speeds table with mode, damped frequency [Hz / rpm], log-decrement.
- AC4: API 684 compliance table with separation margin column.
- AC5: explicit "API 684 2nd ed. §2.7.1.7 Figure 2-8" citation text on page.
- Footer: "Generated by Cascade v[version]. Not a substitute for qualified engineering
  review. See /docs/validation for solver validation status. © American Turbines."

References
----------
- API Std 684, 2nd ed. (2019), §2.7.1.7 Figure 2-8.
- reportlab 4.x docs (https://docs.reportlab.com/reportlab/userguide/).
"""

from __future__ import annotations

import io
import math
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

# reportlab imports — added to pyproject.toml [project.optional-dependencies] pdf
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.platypus import Table, TableStyle


# ---------------------------------------------------------------------------
# Layout constants
# ---------------------------------------------------------------------------

_PAGE_W, _PAGE_H = letter  # 8.5 × 11 inches
_MARGIN_L = 0.75 * inch
_MARGIN_R = _PAGE_W - 0.75 * inch
_CONTENT_W = _MARGIN_R - _MARGIN_L

# Colour palette — all reportlab Color objects
_COL_HEADING = colors.HexColor("#1a2940")   # dark navy
_COL_PASS = colors.HexColor("#166534")      # dark green
_COL_FAIL = colors.HexColor("#991b1b")      # dark red
_COL_ROW_ALT = colors.HexColor("#f3f6fa")   # very light blue-gray
_COL_BORDER = colors.HexColor("#c8d3e0")
_COL_WATERMARK = colors.Color(0.75, 0.75, 0.75, alpha=0.35)  # light gray, semi-transparent


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _draw_watermark(c: rl_canvas.Canvas) -> None:
    """Diagonal 'PRELIMINARY — NOT FOR CERTIFICATION' across the full page."""
    c.saveState()
    c.setFillColor(_COL_WATERMARK)
    # Rotate around page centre; font size chosen so text spans most of the page.
    c.translate(_PAGE_W / 2.0, _PAGE_H / 2.0)
    c.rotate(45)
    c.setFont("Helvetica-Bold", 34)
    text = "PRELIMINARY — NOT FOR CERTIFICATION"
    c.drawCentredString(0, 0, text)
    c.restoreState()


def _draw_header(c: rl_canvas.Canvas, project_name: str, shape_summary: Optional[Dict[str, Any]]) -> float:
    """Draw the page header and project metadata.  Returns the y cursor after header."""
    y = _PAGE_H - 0.55 * inch

    # ---- Main title ----
    c.setFont("Helvetica-Bold", 13)
    c.setFillColor(_COL_HEADING)
    c.drawString(_MARGIN_L, y, "Rotor Dynamics Report — Cascade Preliminary Design Tool")

    y -= 0.22 * inch
    c.setFont("Helvetica", 8.5)
    c.setFillColor(colors.HexColor("#555555"))
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    c.drawString(_MARGIN_L, y, f"Project: {project_name}    |    Generated: {date_str}")

    # Rotor geometry metadata line
    if shape_summary:
        n_sections = len(shape_summary.get("sections", []))
        materials = list({s.get("material", "—") for s in shape_summary.get("sections", [])})
        mat_str = ", ".join(sorted(materials)) if materials else "—"
        total_mass = shape_summary.get("total_mass_kg", 0.0)
        total_len = shape_summary.get("total_length_m", 0.0)
        y -= 0.16 * inch
        c.setFont("Helvetica", 8)
        c.drawString(
            _MARGIN_L,
            y,
            f"Sections: {n_sections}  |  Material(s): {mat_str}  |  "
            f"Total mass: {total_mass:.3f} kg  |  Total length: {total_len * 1000:.1f} mm",
        )

    # Horizontal rule
    y -= 0.18 * inch
    c.setStrokeColor(_COL_BORDER)
    c.setLineWidth(0.5)
    c.line(_MARGIN_L, y, _MARGIN_R, y)
    y -= 0.12 * inch
    return y


def _draw_section_title(c: rl_canvas.Canvas, y: float, title: str) -> float:
    c.setFont("Helvetica-Bold", 9)
    c.setFillColor(_COL_HEADING)
    c.drawString(_MARGIN_L, y, title)
    y -= 0.05 * inch
    c.setStrokeColor(_COL_HEADING)
    c.setLineWidth(0.3)
    c.line(_MARGIN_L, y, _MARGIN_R, y)
    y -= 0.12 * inch
    return y


def _table_to_canvas(
    c: rl_canvas.Canvas,
    data: List[List[str]],
    col_widths: List[float],
    y: float,
    row_heights: float = 0.175 * inch,
) -> float:
    """Render a Table via platypus and stamp it onto the canvas at (MARGIN_L, y).

    Returns the y position below the table.
    """
    tbl = Table(
        data,
        colWidths=col_widths,
        rowHeights=[row_heights] * len(data),
    )
    # Header row style
    n_rows = len(data)
    style = TableStyle(
        [
            # Header
            ("BACKGROUND", (0, 0), (-1, 0), _COL_HEADING),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 7.5),
            ("TOPPADDING", (0, 0), (-1, 0), 3),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 3),
            # Data rows
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 1), (-1, -1), 7.5),
            ("TOPPADDING", (0, 1), (-1, -1), 2),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 2),
            # Borders
            ("GRID", (0, 0), (-1, -1), 0.3, _COL_BORDER),
            ("LINEBELOW", (0, 0), (-1, 0), 0.5, _COL_HEADING),
            # Alternating row tints (even data rows)
            *[
                ("BACKGROUND", (0, r), (-1, r), _COL_ROW_ALT)
                for r in range(2, n_rows, 2)
            ],
            # Alignment
            ("ALIGN", (0, 0), (0, -1), "CENTER"),
            ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]
    )
    tbl.setStyle(style)
    w, h = tbl.wrapOn(c, _CONTENT_W, _PAGE_H)
    tbl.drawOn(c, _MARGIN_L, y - h)
    return y - h - 0.05 * inch


def _draw_footer(c: rl_canvas.Canvas, cascade_version: str) -> None:
    """Draw the footer at the bottom of the page."""
    y = 0.45 * inch
    c.setStrokeColor(_COL_BORDER)
    c.setLineWidth(0.4)
    c.line(_MARGIN_L, y + 0.10 * inch, _MARGIN_R, y + 0.10 * inch)
    c.setFont("Helvetica", 6.5)
    c.setFillColor(colors.HexColor("#777777"))
    footer_text = (
        f"Generated by Cascade v{cascade_version}. Not a substitute for qualified engineering review. "
        f"See /docs/validation for solver validation status. © American Turbines."
    )
    c.drawString(_MARGIN_L, y, footer_text)
    # Citation line
    c.drawString(
        _MARGIN_L,
        y - 0.15 * inch,
        "API 684 2nd ed. §2.7.1.7 Figure 2-8 — separation margin vs amplification factor.",
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_rotor_pdf(
    project_name: str,
    modes: List[Dict[str, Any]],
    compliance: Optional[Dict[str, Any]],
    shape_summary: Optional[Dict[str, Any]],
    cascade_version: str = "0.1.0",
) -> bytes:
    """Generate a one-page US-Letter PDF and return the bytes.

    Parameters
    ----------
    project_name:
        Human-readable project name shown in the header.
    modes:
        List of serialised mode dicts from ``_serialize_mode`` (rotor router).
        Must contain at least: mode_index, frequency_hz, frequency_rpm,
        log_decrement, whirl, shape_name.
    compliance:
        Dict from ``_compliance_report`` (rotor router).  May be None or
        contain an empty ``criticals`` list.
    shape_summary:
        Dict from ``_shape_summary`` (rotor router).  May be None.
    cascade_version:
        String version injected into the footer.

    Returns
    -------
    bytes
        Raw PDF binary.
    """
    buf = io.BytesIO()
    c = rl_canvas.Canvas(buf, pagesize=letter)

    # --- Watermark (behind everything) ---
    _draw_watermark(c)

    # --- Header ---
    y = _draw_header(c, project_name, shape_summary)

    # -------------------------------------------------------------------------
    # Section 1: Critical-speed / mode table
    # -------------------------------------------------------------------------
    y = _draw_section_title(c, y, "Critical Speeds and Modal Parameters")

    if modes:
        headers = ["Mode", "Shape", "Freq (Hz)", "Freq (rpm)", "Whirl", "Log Dec"]
        col_widths = [
            0.55 * inch,
            0.85 * inch,
            0.80 * inch,
            0.85 * inch,
            0.85 * inch,
            0.65 * inch,
        ]
        # Pad remaining width evenly if needed (safety)
        used = sum(col_widths)
        if used < _CONTENT_W:
            col_widths[-1] += _CONTENT_W - used

        rows: List[List[str]] = [headers]
        for m in modes:
            log_dec = m.get("log_decrement")
            log_dec_str = f"{log_dec:.3f}" if (log_dec is not None and math.isfinite(log_dec)) else "—"
            freq_rpm = m.get("frequency_rpm")
            freq_rpm_str = f"{freq_rpm:,.0f}" if (freq_rpm is not None and math.isfinite(float(freq_rpm))) else "—"
            rows.append(
                [
                    str(int(m.get("mode_index", 0)) + 1),
                    str(m.get("shape_name", "—")),
                    f"{float(m.get('frequency_hz', 0)):.2f}",
                    freq_rpm_str,
                    str(m.get("whirl", "—")),
                    log_dec_str,
                ]
            )
        y = _table_to_canvas(c, rows, col_widths, y)
    else:
        c.setFont("Helvetica-Oblique", 8)
        c.setFillColor(colors.HexColor("#888888"))
        c.drawString(_MARGIN_L, y, "No modal results available. Run a lateral analysis first.")
        y -= 0.25 * inch

    y -= 0.10 * inch  # gap between sections

    # -------------------------------------------------------------------------
    # Section 2: API 684 compliance table
    # -------------------------------------------------------------------------
    y = _draw_section_title(c, y, "API 684 §2.7.1.7 Compliance — Separation Margin")

    criticals = (compliance or {}).get("criticals", [])
    operating_rpm = (compliance or {}).get("operating_speed_rpm", 0.0)
    speed_range = (compliance or {}).get("speed_range_rpm", [0.0, 0.0])

    if compliance and criticals:
        headers2 = [
            "Critical rpm",
            "Mode",
            "Whirl",
            "AF",
            "Actual SM (%)",
            "Req SM (%)",
            "Pass/Fail",
            "API Clause",
        ]
        col2_widths = [
            0.80 * inch,
            0.50 * inch,
            0.60 * inch,
            0.45 * inch,
            0.75 * inch,
            0.75 * inch,
            0.60 * inch,
            0.85 * inch,
        ]
        used2 = sum(col2_widths)
        if used2 < _CONTENT_W:
            col2_widths[0] += _CONTENT_W - used2

        rows2: List[List[str]] = [headers2]
        for crit in criticals:
            passes = bool(crit.get("passes", False))
            rows2.append(
                [
                    f"{float(crit.get('rpm', 0)):,.0f}",
                    str(int(crit.get("mode_id", 0)) + 1),
                    str(crit.get("whirl", "—")),
                    f"{float(crit.get('amplification_factor', 0)):.2f}",
                    f"{float(crit.get('separation_margin_pct', 0)):.1f}",
                    f"{float(crit.get('required_margin_pct', 0)):.1f}",
                    "PASS" if passes else "FAIL",
                    str(crit.get("api_clause", "API 684 §2.7.1.7")),
                ]
            )

        # Build table then colour-code pass/fail cells
        tbl2 = Table(
            rows2,
            colWidths=col2_widths,
            rowHeights=[0.175 * inch] * len(rows2),
        )
        n2 = len(rows2)
        style2_cmds = [
            ("BACKGROUND", (0, 0), (-1, 0), _COL_HEADING),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 7.5),
            ("TOPPADDING", (0, 0), (-1, 0), 3),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 3),
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 1), (-1, -1), 7.5),
            ("TOPPADDING", (0, 1), (-1, -1), 2),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 2),
            ("GRID", (0, 0), (-1, -1), 0.3, _COL_BORDER),
            ("LINEBELOW", (0, 0), (-1, 0), 0.5, _COL_HEADING),
            ("ALIGN", (0, 0), (-1, 0), "CENTER"),
            ("ALIGN", (0, 1), (-1, -1), "RIGHT"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]
        for r in range(2, n2, 2):
            style2_cmds.append(("BACKGROUND", (0, r), (-1, r), _COL_ROW_ALT))
        # Colour the pass/fail column (index 6)
        for r in range(1, n2):
            passes_row = rows2[r][6] == "PASS"
            col = _COL_PASS if passes_row else _COL_FAIL
            style2_cmds.append(("TEXTCOLOR", (6, r), (6, r), col))
            style2_cmds.append(("FONTNAME", (6, r), (6, r), "Helvetica-Bold"))

        tbl2.setStyle(TableStyle(style2_cmds))
        w2, h2 = tbl2.wrapOn(c, _CONTENT_W, _PAGE_H)
        tbl2.drawOn(c, _MARGIN_L, y - h2)
        y = y - h2 - 0.07 * inch

        # Operating speed note
        c.setFont("Helvetica", 7.5)
        c.setFillColor(colors.HexColor("#444444"))
        c.drawString(
            _MARGIN_L,
            y,
            f"Operating speed: {operating_rpm:,.0f} rpm  |  Speed range: "
            f"{float(speed_range[0]):,.0f} – {float(speed_range[1]):,.0f} rpm",
        )
        y -= 0.18 * inch

    elif compliance:
        # Compliance object present but no crossings
        c.setFont("Helvetica-Oblique", 8)
        c.setFillColor(colors.HexColor("#166534"))
        c.drawString(
            _MARGIN_L,
            y,
            f"No critical-speed crossings within the operating range "
            f"({float(speed_range[0]):,.0f} – {float(speed_range[1]):,.0f} rpm). API 684 §2.7.1.7 — no separation margin check required.",
        )
        y -= 0.25 * inch
    else:
        c.setFont("Helvetica-Oblique", 8)
        c.setFillColor(colors.HexColor("#888888"))
        c.drawString(_MARGIN_L, y, "No compliance data available. Run a lateral analysis first.")
        y -= 0.25 * inch

    # -------------------------------------------------------------------------
    # Footer (fixed at bottom of page)
    # -------------------------------------------------------------------------
    _draw_footer(c, cascade_version)

    c.save()
    return buf.getvalue()
